"""Draft-PR publisher — push the team's branch and open a GitHub PR.

This is the "release step" of a scrum campaign for real deployments.
Runs at the end of run_campaign() when --open-pr is set. Fails gracefully
if any prerequisite is missing (no remote, `gh` not installed, push fails).

Uses the GitHub CLI (`gh`) to open a draft PR. Draft on purpose — nothing
that agents produce should auto-merge without human review.

Public entrypoint:
    open_pr_for_team(workspace, base="main", extra_body="") → PublishResult
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from orgos.agile.team_workspace import TeamWorkspace


@dataclass
class PublishResult:
    published: bool
    pr_url: str = ""
    skipped_reason: str = ""
    error: str = ""


def _run(cmd: list[str], cwd: Path, timeout: int = 60) -> tuple[int, str, str]:
    """Run a subprocess. Return (returncode, stdout, stderr) — never raises."""
    try:
        r = subprocess.run(
            cmd, cwd=str(cwd), capture_output=True, text=True, timeout=timeout,
        )
        return r.returncode, (r.stdout or "").strip(), (r.stderr or "").strip()
    except FileNotFoundError:
        return 127, "", f"command not found: {cmd[0]}"
    except subprocess.TimeoutExpired:
        return 124, "", f"timeout after {timeout}s: {' '.join(cmd)}"
    except Exception as e:
        return 1, "", f"{type(e).__name__}: {e}"


def _has_commits_beyond_baseline(worktree: Path, baseline_sha: str) -> bool:
    """True if the branch has any commit AFTER the baseline (not counting it)."""
    rc, out, _ = _run(
        ["git", "rev-list", "--count", f"{baseline_sha}..HEAD"], worktree,
    )
    if rc != 0:
        return False
    try:
        return int(out.strip() or "0") > 0
    except ValueError:
        return False


def _get_origin_url(worktree: Path) -> str:
    rc, out, _ = _run(["git", "remote", "get-url", "origin"], worktree)
    return out if rc == 0 else ""


def _push_branch(worktree: Path, branch: str) -> tuple[bool, str]:
    """Push branch to origin. Returns (ok, message)."""
    rc, out, err = _run(
        ["git", "push", "-u", "origin", branch, "--force-with-lease"],
        worktree, timeout=120,
    )
    if rc == 0:
        return True, out or "pushed"
    return False, err or f"push failed (rc={rc})"


def _gh_available() -> bool:
    return shutil.which("gh") is not None


def _open_pr_via_gh(worktree: Path, base: str, title: str, body: str,
                     branch: str) -> tuple[bool, str, str]:
    """Call `gh pr create --draft`. Returns (ok, url_or_msg, error)."""
    rc, out, err = _run(
        [
            "gh", "pr", "create",
            "--draft",
            "--title", title,
            "--body", body,
            "--head", branch,
            "--base", base,
        ],
        worktree, timeout=120,
    )
    if rc == 0:
        # gh prints the URL as its stdout on success
        return True, out.strip(), ""
    return False, "", err or f"gh pr create failed (rc={rc})"


def _default_pr_body(workspace: TeamWorkspace) -> str:
    """Auto-generate a PR body from the team's manifest + campaign result."""
    m = workspace.manifest()
    lines = [
        f"## Goal",
        "",
        m.goal,
        "",
        f"## Team",
        "",
        f"- **team_id**: `{workspace.team_id}`",
        f"- **model**: `{m.model}`",
        f"- **branch**: `{m.branch}`",
        f"- **baseline**: `{m.baseline_sha[:10]}`",
        "",
        f"## Live report",
        "",
        "See `.orgos_teams/{}/report.html` (self-contained; open in browser).".format(
            workspace.team_id,
        ),
        "",
        "---",
        "",
        "🤖 Generated by the orgos Agent Scrum Team Platform. Draft PR — "
        "requires human review before merge.",
    ]
    return "\n".join(lines)


def open_pr_for_team(
    workspace: TeamWorkspace,
    *,
    base: str = "main",
    title: Optional[str] = None,
    body: Optional[str] = None,
) -> PublishResult:
    """Push the team's branch and open a draft PR.

    Fails gracefully:
      - No commits on branch → skipped ("nothing to publish")
      - No `gh` CLI installed → skipped ("gh not available")
      - No `origin` remote → skipped ("no origin")
      - Push or gh call fails → error captured
    """
    m = workspace.manifest()

    # 1. Anything to publish?
    if not _has_commits_beyond_baseline(workspace.worktree, m.baseline_sha):
        return PublishResult(
            published=False,
            skipped_reason="no commits on branch — nothing to publish",
        )

    # 2. Remote configured?
    origin = _get_origin_url(workspace.worktree)
    if not origin:
        return PublishResult(
            published=False,
            skipped_reason="no `origin` remote — set one with "
                           "`git remote add origin <url>` to enable PR opening",
        )

    # 3. gh available?
    if not _gh_available():
        return PublishResult(
            published=False,
            skipped_reason="`gh` CLI not installed. Install: "
                           "https://cli.github.com/. Once installed, run "
                           "`gh auth login` before retrying.",
        )

    # 4. Push
    ok, push_msg = _push_branch(workspace.worktree, m.branch)
    if not ok:
        return PublishResult(
            published=False, error=f"push failed: {push_msg}",
        )

    # 5. Open PR
    pr_title = title or f"[orgos/{workspace.team_id}] {m.goal[:60]}"
    pr_body = body or _default_pr_body(workspace)
    ok, url, err = _open_pr_via_gh(
        workspace.worktree, base=base, title=pr_title,
        body=pr_body, branch=m.branch,
    )
    if not ok:
        return PublishResult(published=False, error=err)

    # Persist pr_url so mid-run ceremonies (e.g. PO's pr_feedback) can find it
    # without waiting for campaign_result.json which is only written on shutdown.
    try:
        (workspace.root / "pr_url.txt").write_text(url, encoding="utf-8")
    except Exception:
        pass

    return PublishResult(published=True, pr_url=url)
